SET ThousandSep=' ';
SET DecimalSep=',';
SET MoneyThousandSep='.';
SET MoneyDecimalSep=',';
SET MoneyFormat='€ #.##0,00;-€ #.##0,00';
SET TimeFormat='hh:mm:ss';
SET DateFormat='DD.MM.YYYY';
SET TimestampFormat='DD.MM.YYYY hh:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=0;
SET ReferenceDay=4;
SET FirstMonthOfYear=1;
SET CollationLocale='de-AT';
SET CreateSearchIndexOnReload=0;  // <-- during development set to 0
SET MonthNames='Jän.;Feb.;März;Apr.;Mai;Juni;Juli;Aug.;Sep.;Okt.;Nov.;Dez.';
SET LongMonthNames='Jänner;Februar;März;April;Mai;Juni;Juli;August;September;Oktober;November;Dezember';
SET DayNames='Mo.;Di.;Mi.;Do.;Fr.;Sa.;So.';
SET LongDayNames='Montag;Dienstag;Mittwoch;Donnerstag;Freitag;Samstag;Sonntag';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

IF vScriptFolder = 'preview' THEN
    LET vQVDLoadFolder = 'lib://D-QVD-test/KST/1.Extract';
    LET vQVDSaveToFolder = 'lib://D-QVD-test/KST/2.Transform';
ELSE
    LET vQVDLoadFolder = 'lib://D-QVD-prod/KST/1.Extract';
    LET vQVDSaveToFolder = 'lib://D-QVD-prod/KST/2.Transform';
ENDIF

reload: 
LOAD Now() AS StartReloadAt AUTOGENERATE(1);

$(must_include=[lib://include-script-library/get-custom-prop.css]);
CALL getCustomProp ('QRS-API GET', 'ScriptFolder', 'v', 1, 0);

//SET HidePrefix = '%';

// Build a list of vYears from current year back to 2020 in this format: '2022', '2021', '2020'
LET vYears = '';
FOR vYear = Year(Today()) TO 2019 STEP -1;
  LET vYears = vYears & If(Len(vYears), ',') & CHR(39) & vYear & CHR(39);
NEXT vYear
TRACE vYears: $(vYears);

//SET vYears = ['2022', '2021'];
