LET vStartYear = Year(Today());
LET vEndYear = RangeMax(2020, Year(Today()) -3);  // history starts in 2020
TRACE Years $(vStartYear) TO $(vEndYear) ;


FOR vYear = $(vStartYear) TO $(vEndYear) STEP -1
	FOR vMonth = 12 TO 1 STEP -1
    	LET vMonth2 = Text(Num(vMonth, '00'));
    	LET vYearMonth = '$(vYear)-$(vMonth2)';
        
    	IF MakeDate(vYear, vMonth, 1) <= MonthStart(Today()) THEN
            
            LET vBasketsQVD = Lookup('qvd_count_posbasket+item', 'year_month', vYearMonth, 'Counting_rows');
            LET vBasketsSQL = Lookup('sql_count', 'year_month', vYearMonth, 'Counting_rows');
            LET vGoSQL = Fabs(Len(vBasketsSQL) AND vBasketsSQL <> vBasketsQVD OR vForceLoadAll);
            
            TRACE $(vYearMonth): $(vBasketsSQL) SQL , $(vBasketsQVD) QVD --> SQL? $(vGoSQL);
            
            IF vGoSQL THEN
 				CALL ProcessMonth (vYearMonth);
			END IF
        END IF

    NEXT vMonth
NEXT vYear    

