// Schnepf-Kassa Daten laden

// Zunächst nur alle in der Kassa Invoice vorkommenden Site_Numbers als Station hinzufügen
// in die "location" tabelle, mit Default Namen und Default Stations-Nummer

location:
LOAD DISTINCT
    //'SK|' & invoice.service_station                     AS %locationId
    'SK|' & invoice.site_number                     AS %locationId

    ,'Schnepf Kassa #' & invoice.site_number        AS location.name.default
    ,'MELZ' & invoice.site_number                   AS [Stations-Nummer.default]
FROM 
	[$(vQVDLoadFolder)/schnepf_invoice+item.qvd] (qvd)
;

// Jetzt berechern wir die aus der Invoice stammenden site_numbers mit den (hoffentlich
// vollständig gefüllten) "Schnepf Kassen" Mapping vom Sharepoint Excel

LEFT JOIN (location)
LOAD 
// JOIN ON
	'SK|' & site_number                 AS %locationId
// ADD FIELDS
    ,MixMatch(importieren, 'J','Y','1') AS location.import.mapped
    ,Tankstelle                         AS location.name.mapped
    ,[Stations-Nummer]                  AS [Stations-Nummer.mapped]
// Mapping für Melzer (Schnepf) Kassen Locations Stationen
FROM 
    [$(vBerechtigungenExcel)] 
    (ooxml, embedded labels, table is [Schnepf Kassen], header is 1 lines);

// Finales "Überladen" der location Tabelle, wobei der .mapped Name und .mapped Stations-Nummer
// immer über die .default gewinnt, sofern vorhanden.
// Für Melzer Kassendaten gibt es ein Flag, ob die Station importiert werden soll

// STORE location INTO [$(vQVDSaveToFolder)/~melzer_locations.txt] (txt, delimiter is '\t'); 



location2:
LOAD 
	*
    ,Coalesce(location.name.mapped, location.name.default)          AS location.name2
    ,Coalesce([Stations-Nummer.mapped], [Stations-Nummer.default])  AS [Stations-Nummer2]
RESIDENT
	location
WHERE
    Alt(location.import.mapped, True()); 
    
// STORE location2 INTO [$(vQVDSaveToFolder)/~melzer_locations2.txt] (txt, delimiter is '\t'); 

DROP TABLE location;
RENAME TABLE location2 TO location;

DROP FIELDS 
    location.name.mapped, location.name.default, location.import.mapped
    FROM location;

DROP FIELDS 
    [Stations-Nummer.mapped], [Stations-Nummer.default] 
    FROM location;

RENAME FIELD [location.name2] TO location.name;
RENAME FIELD [Stations-Nummer2] TO [Stations-Nummer];


STORE location INTO [$(vQVDSaveToFolder)/location.qvd] (qvd);
CALL GetQvdFieldNames('location', vQVDSaveToFolder);

    
