/*
Nachdem es keine eigene Produkt-Tabelle bei Schnepf Kassen gibt, werden Produkte aus
den invoice+item Zeilen herausgelesen.
*/

product:
LOAD DISTINCT
    'Schnepf'                                                     AS product.source
    ,0                                                            AS product.isFuel
    ,'SK|' & Lower(Left(KeepChar(Repeat(Hash256(item.product_description)&'-',10)   
    	,'0123456789ABCDEFGHIJKLMOPQRSTUVWXYZ-'), 36))            AS %prodMappingId  
	,'SK|' & $(vMelzerProductID_Syntax)                           AS %productId
    ,$(vMelzerProductID_Syntax)                                   AS product.uid
    ,item.product_description                                     AS product.name
    ,'SK|' & $(vMelzerProdGrp_Syntax)                             AS %prodGrpId
FROM 
	[$(vQVDLoadFolder)/schnepf_invoice+item.qvd] (qvd)
;



STORE product INTO [$(vQVDSaveToFolder)/product.qvd] (qvd);
CALL GetQvdFieldNames('product', vQVDSaveToFolder);
