SET ThousandSep=' ';
SET DecimalSep=',';
SET MoneyThousandSep='.';
SET MoneyDecimalSep=',';
SET MoneyFormat='€ #.##0,00;-€ #.##0,00';
SET TimeFormat='hh:mm:ss';
SET DateFormat='DD.MM.YYYY';
SET TimestampFormat='DD.MM.YYYY hh:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=0;
SET ReferenceDay=4;
SET FirstMonthOfYear=1;
SET CollationLocale='de-AT';
SET CreateSearchIndexOnReload=1;  // <-- set to 0 during development
SET MonthNames='Jän.;Feb.;März;Apr.;Mai;Juni;Juli;Aug.;Sep.;Okt.;Nov.;Dez.';
SET LongMonthNames='Jänner;Februar;März;April;Mai;Juni;Juli;August;September;Oktober;November;Dezember';
SET DayNames='Mo.;Di.;Mi.;Do.;Fr.;Sa.;So.';
SET LongDayNames='Montag;Dienstag;Mittwoch;Donnerstag;Freitag;Samstag;Sonntag';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

SEARCH INCLUDE '*';
SEARCH EXCLUDE '%*', '*uid', '*REF_*', '*_date', '*.id', '*.ID', '*PrintAdditional', 'item.*';

//SET vPublicAppId = 8131e9ec-e226-4ab5-8fd6-dd8cde42acbf;

SET vBerechtigungenExcel = [lib://Office_365_Sharepoint/Freigegebene Dokumente/Qlik Files/ROHDATEN FÜR SICHTUNG/MAPPINGS/UserTankstellen+SheetsMapping.xlsx];
IF vScriptFolder = 'preview' THEN
    SET vQvdPath_Transf_Monalisa = [lib://D-QVD-test/Monalisa/2.Transform];
    SET vQvdPath_Transf_KST      = [lib://D-QVD-test/KST/2.Transform];
    SET vQvdPath_Transf_Schnepf  = [lib://D-QVD-test/Schnepf/2.Transform];
    SET vQvdPath_Store           = [lib://D-QVD-test/Combined];
ELSE
    SET vQvdPath_Transf_Monalisa = [lib://D-QVD-prod/Monalisa/2.Transform];
    SET vQvdPath_Transf_KST      = [lib://D-QVD-prod/KST/2.Transform];
    SET vQvdPath_Transf_Schnepf  = [lib://D-QVD-prod/Schnepf/2.Transform];
    SET vQvdPath_Store           = [lib://D-QVD-prod/Combined];
ENDIF

reload: 
LOAD Now() AS StartReloadAt AUTOGENERATE(1);
