SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

LET dbSchema = 'kstStationData.kst';
IF vScriptFolder = 'preview' THEN
    LET saveTo = 'lib://D-QVD-test/KST/1.Extract';
ELSE
    LET saveTo = 'lib://D-QVD-prod/KST/1.Extract';
ENDIF

LET vForceLoadAll = Weekday(Today()) = 'Sun'; // full-load on Sundays 
LET vCutoffDate = '20200101';  // Ab diesem Datum werden Baskets und Items abgefragt
Reload: LOAD Now() AS ScriptStart AUTOGENERATE(1);

LIB CONNECT TO 'kstStationData SQL Database';
