
CONCATENATE (product)
LOAD
	*
    ,0                                                             AS product.isFuel
    ,'Schnepf'                                                     AS product.source
    ,'SK|' & product.uid                                           AS %productId
    ,'SK|' & product.uid                                           AS %prodMappingId  // in Monalisa the %prodMappingId and %productId are the same, in KST not 
;
LOAD
    Lower(Left(KeepChar(Repeat(Hash256(item.product_description)&'-',10)   
    	,'0123456789ABCDEFGHIJKLMOPQRSTUVWXYZ-'), 36))             AS product.uid
	,item.product_description                                      AS product.name
    ,Concat(DISTINCT item.product_number, ',')                     AS product.melzer_product_id
    ,'SK|' & Only(item.melzer_product_group)                       AS %prodGrpId
FROM 
	[$(vQVDLoadFolder)/schnepf_invoice+item.qvd] (qvd)
GROUP BY
    item.product_description
;


// STORE von product als QVD ist in script 2M50
