


MelzerProduktgruppen:
// feld "sub-path" muss zumindest eine Unterkategorie unter "Gastronomie" enthalten
// (das wird zu productgroup.name2) aber kann auch noch "\" und eine weitere 
// Unterkategorie  (das wird zu productgroup.name2) enthalten
MAPPING LOAD 
    Text([Produktgruppe ID])
    ,[Produktgruppe Pfad]
FROM 
    [$(vBerechtigungenExcel)]
    (ooxml, embedded labels, header is 1 lines, table is [Schnepf Produktgruppen])
WHERE 
    WildMatch(Valid, 'J*', '1', 'Y*');

CONCATENATE (productgroup)
LOAD
	[%prodGrpId]
    ,productgroup.uid
    ,SubField(productgroup.lookup, '\', -1)                     AS productgroup.name
    ,SubField(productgroup.lookup, '\', 1)                      AS productgroup.name1
    ,SubField(productgroup.lookup, '\', 2)                      AS productgroup.name2
    ,SubField(productgroup.lookup, '\', 3)                      AS productgroup.name3
    ,productgroup.lookup                                        AS productgroup.Path
    ,1 + SubStringCount(productgroup.lookup, '\')               AS productgroup.hier_level
    ,'True'                                                     AS productgroup.valid
    ,productgroup.isSchnepfXlsMapping                           AS productgroup.isSchnepfXlsMapping
;
LOAD
	'SK|' & item.melzer_product_group                           AS %prodGrpId
    ,item.melzer_product_group                                  AS productgroup.uid
    ,NOT IsNull(ApplyMap('MelzerProduktgruppen', Text(item.melzer_product_group), Null()))
                                                                AS productgroup.isSchnepfXlsMapping
    ,Only(ApplyMap('MelzerProduktgruppen', Text(item.melzer_product_group),
    	 'Gastronomie\Schnepf Kassa Gruppe ' & item.melzer_product_group))   
                                                                AS productgroup.lookup
FROM 
	[$(vQVDLoadFolder)/schnepf_invoice+item.qvd] (qvd)
GROUP BY
    item.melzer_product_group;
    


STORE productgroup INTO [$(vQVDSaveToFolder)/productgroup.qvd] (qvd);
CALL GetQvdFieldNames('productgroup', vQVDSaveToFolder);
