// Version 18-Feb-2025
// neu erstellt, der Extrakt von Schnepf Melzer Kassendaten war zuvor Teil von Extract Monalisa, hat aber
// nichts damit zu tun (eigene Datenquellen und eigene ETL Prozesse), so dass es hier herausgesplittet wird.

SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='hh:mm:ss';
SET DateFormat='YYYY-MM-DD';
SET TimestampFormat='YYYY-MM-DD hh:mm:ss[.fff]';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=0;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

LIB CONNECT TO 'MonaLisaPROD Database';

Reload: LOAD Now() AS ScriptStart AUTOGENERATE(1);

// vScriptFolder variable wird von get-custom-props.css include-script gesetzt.
// script found here https://bi.stiglechner.at/dev-hub/extension-editor/#qext{qlik-script-lib}
 
LET dbSchema = 'mona';
IF vScriptFolder = 'preview' THEN
    LET vQVDSaveToFolder = 'lib://D-QVD-test/Schnepf/1.Extract';
ELSE
    LET vQVDSaveToFolder = 'lib://D-QVD-prod/Schnepf/1.Extract';
ENDIF

